### ISSUE TITLE
Does not build on Xcode 6.2

### ISSUE THREAD

**Issue by cbertelli** [klep/scanline#24]
Hello,
I tried to runt scanline on MacOS 9.5 and got this error:

dyld: Symbol not found: ___NSArray0__
  Referenced from: /Users/user/bin/scanline
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/user/bin/scanline
Trace/BPT trap: 5

I got the source and tried to build it, but it was not compatible with this old Xcode.
I see there are not old branches on github (only the master branch) either.
Do you have a suggestion?

**Comment by klep** [comment]
There were no other branches -- everything is on `master`. So you could attempt to go back to an earlier `master` commit and see if that works. Alternatively, you could start a new project in XCode 6 and try to compile the current source, but that's going to be a very old version of Swift that likely isn't compatible.

**Comment by cbertelli** [comment]
Yes, I found that commit 4612511ff1888e3171ea6622880ea6e08ec6637b builds on XCode 6 (MacOS 10.9). Thank you.
